# Generated by Django 3.2.18 on 2023-02-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('image', models.ImageField(default='profile/default.jpeg', null=True, upload_to='profile')),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GetInTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('body', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=123)),
                ('side', models.CharField(choices=[('left', 'left'), ('right', 'right')], max_length=5, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(max_length=27, null=True)),
                ('body', models.CharField(max_length=500, null=True)),
                ('link', models.CharField(max_length=255, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['published'],
            },
        ),
        migrations.CreateModel(
            name='MyResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='resume.pdf', upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='MySkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyWorkExprea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['published'],
            },
        ),
    ]
